# Generated by Django 5.2.11 on 2026-03-26 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artisan',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='back_image',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='created_at',
        ),
    ]
